
test:
    variables:
        DATABASE_URL : "postgres://postgres:@postgres:5432/omega"
    script:
        - apt-get update -qy
        - apt-get install -y python3-dev python3-pip
        - pip3 install -r requirements.txt
        - pytest
