test:
  services:
  - postgres:"9.6"
  script:
  - export DJANGO_SETTINGS_MODULE="omega.settings.gitlabci"
  - export DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - pytest
