language: python
python:
  - '3.5'

addons:
  postgresql: "9.6"

branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="omega.settings.travis"

script:
  - pytest
