# Generated by Django 2.1.1 on 2018-10-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nutrition_grades', models.CharField(max_length=1)),
                ('nova_group', models.CharField(max_length=1)),
                ('code', models.CharField(max_length=13, unique=True)),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='ersatz.Category')),
            ],
        ),
    ]
