# Generated by Django 2.1.1 on 2018-10-16 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ersatz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nova_group',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
