# Generated by Django 2.1.1 on 2018-10-17 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ersatz', '0003_auto_20181017_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='products',
        ),
        migrations.AddField(
            model_name='favorite',
            name='products',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, related_name='favorites_product', to='ersatz.Product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='substitutes',
        ),
        migrations.AddField(
            model_name='favorite',
            name='substitutes',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, related_name='favorites_substitute', to='ersatz.Product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='users',
        ),
        migrations.AddField(
            model_name='favorite',
            name='users',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, related_name='favorites_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='ersatz.Category'),
        ),
    ]
