# Generated by Django 2.1.1 on 2018-10-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersatz', '0004_auto_20181017_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='ersatz.Category'),
        ),
    ]
