# Generated by Django 2.1.1 on 2018-10-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersatz', '0005_auto_20181017_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_front_thumb_url',
            field=models.CharField(default='https://via.placeholder.com/100x100?text=no+img', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_front_url',
            field=models.CharField(default='https://via.placeholder.com/400x400?text=no+img', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_text',
            field=models.CharField(default='Wotch a kofee avec ton bibalaekaess et ta wurscht ? Yeuh non che suis au réchime, je ne mange plus que des Grumbeere light et che fais de la chym avec Chulien. Tiens, un rottznoz sur le comptoir.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='https://lapoulequimue.fr/?tri=alea', max_length=255),
            preserve_default=False,
        ),
    ]
