# Generated by Django 2.1.1 on 2018-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersatz', '0006_auto_20181020_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_nutrition_url',
            field=models.CharField(default='https://via.placeholder.com/250x100?text=Fiche+OFF+incomplete', max_length=255),
        ),
    ]
