@startuml
title Physical data model\n

/' = = = = = = = STYLE = = = = = = = '/
hide empty methods
hide circle
skinparam linetype ortho
skinparam class {
    BackgroundColor<<assoc>> lightblue
    BackgroundColor<<django>> lightgreen
}

/' = = = = = = = MACRO = = = = = = = '/
!define rel(a,b,c,d,e) a c e
!define pyk(n,t="INT NOT NULL UNSIGNED") <font color="red">PK:<b>n</b> <size:09>[t]</size></font>
!define fnk(n,r,t="INT NOT NULL UNSIGNED") <font color="blue">FK:<b>n</b> <size:09>[t]</size></font>
!define fpk(n,r,t="INT NOT NULL UNSIGNED") <font color="green">PFK:<b>n</b> <size:09>[t]</size></font>
!define att(n,u,s) {field} <b>n</b> [s]

/' = = = = = = = CLASSE = = = = = = = '/
class Category
class CategoryProduct <<assoc>>
class Favorite <<assoc>>
class Product
class User <<django>>


/' = = = = = = = RELATION = = = = = = = '/
rel(Product,1..,--,1..*,CategoryProduct)
rel(CategoryProduct,1..*,--,1..,Category)
rel(User,1..,-up-,1..*,Favorite)
rel(Product,1..*,--,1..*,Favorite)
rel(Product,1..*,-,1..*,Favorite)


/' = = = = = = = KEY = = = = = = = '/
class Category {
    pyk(id)
    ..
}

class CategoryProduct {
    pyk(id)
    ..
    fnk(product_id,product.id)
    fnk(category_id,category.id)
}

class Favorite {
    pyk(id)
    ..
    fnk(products,product.id)
    fnk(substitutes,product.id)
    fnk(users,user.id)
}

class Product {
    pyk(id)
    ..
    fnk(category_id,category.id)
    ..
}

class User {
    pyk(id)
    ..
}


/' = = = = = = = ATTRIBUTE = = = = = = = '/
class Category {
    att(name,String,VARCHAR(200) UNIQUE NOT NULL)
}

class Product {
    att(code,String,VARCHAR(13) UNIQUE NOT NULL)
    att(image_front_thumb_url,String,VARCHAR(255))
    att(image_front_url,String,VARCHAR(255))
    att(image_nutrition_url,String,VARCHAR(255))
    att(name,String,VARCHAR(200))
    att(nutrition_grades,String,VARCHAR(1))
    att(url,String,VARCHAR(255))
}

class User {
    att(email,String,VARCHAR(254) NOT NULL)
    att(username,String,VARCHAR(150) NOT NULL)
    att(password,String,VARCHAR(128) NOT NULL)
}
@enduml
