@startuml
title Physical data model\n

/' = = = = = = = STYLE = = = = = = = '/
hide empty methods
hide circle
skinparam linetype ortho
skinparam class {
    BackgroundColor<<assoc>> lightblue
    BackgroundColor<<django>> lightgreen
}

/' = = = = = = = MACRO = = = = = = = '/
!define rel(a,b,c,d,e) a c e
!define pyk(n,t="INT NOT NULL UNSIGNED") <font color="red">PK:<b>n</b> <size:09>[t]</size></font>
!define fnk(n,r,t="INT NOT NULL UNSIGNED") <font color="blue">FK:<b>n</b> <size:09>[t]</size></font>
!define fpk(n,r,t="INT NOT NULL UNSIGNED") <font color="green">PFK:<b>n</b> <size:09>[t]</size></font>
!define att(n,u,s) {field} <b>n</b> [s]

/' = = = = = = = CLASSE = = = = = = = '/
class Category
class CategoryProduct <<assoc>>
class ProductUser <<assoc>>
class Product
class User <<django>>


/' = = = = = = = RELATION = = = = = = = '/
rel(Product,1..,--,1..*,CategoryProduct)
rel(CategoryProduct,1..*,--,1..,Category)
rel(User,1..,-up-,1..*,ProductUser)
rel(Product,1..*,--,1..*,ProductUser)


/' = = = = = = = KEY = = = = = = = '/
class Category {
    pyk(id)
    ..
}

class CategoryProduct {
    pyk(id)
    ..
    fnk(product_id,product.id)
    fnk(category_id,category.id)
}

class ProductUser {
    pyk(id)
    ..
    fnk(product_id,product.id)
    fnk(user_id,user.id)
}

class Product {
    pyk(id)
    ..
    fnk(category_id,category.id)
    ..
}

class User {
    pyk(id)
    ..
}


/' = = = = = = = ATTRIBUTE = = = = = = = '/
class Category {
    att(name,String,VARCHAR(200) NOT NULL)
}

class Product {
    att(name,String,VARCHAR(200) NOT NULL)
    att(code,String,VARCHAR(100) NOT NULL)
    att(nutrition_grades,String,VARCHAR(1) NOT NULL)
    att(nova_group,String,VARCHAR(1) NOT NULL)
}

class User {
    att(email,String,VARCHAR(254) NOT NULL)
    att(username,String,VARCHAR(150) NOT NULL)
    att(last_name,String,VARCHAR(150) NULL)
    att(first_name,String,VARCHAR(30) NULL)
    att(password,String,VARCHAR(128) NOT NULL)
    att(is_superuser,Bool,BOOLEAN)
    att(is_staff,Bool,BOOLEAN)
    att(is_active,Bool,BOOLEAN)
    att(last_login,Integer,TIMESTAMP NULL)
    att(date_joined,Integer,TIMESTAMP NOT NULL)
}
@enduml
