
"""
`settings.py` for travis CI

Django settings for omega project.
Generated by 'django-admin startproject' using Django 2.1.1.
Splitted into specific files by environment after v0.3
"""
from . import *

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': '',
        'PORT': '',
        'NAME': '',
        'USER': 'postgres',
        'PASSWORD':'',
    }
}
